name: Docker Image CI Development
on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    
    - name: Debug secrets
      run: |
        echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "Password set: ${{ secrets.DOCKERHUB_PASSWORD }}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build the Docker image
      run: docker build --target development -t udayagonuguntla/tweakai-dev:dev .
    
    - name: Push Docker image to Docker Hub
      run: docker push udayagonuguntla/tweakai-dev:dev
